In [1]:
list=[1,2,3]
list

[1, 2, 3]

In [2]:
#import libraries
import numpy as np

In [3]:
arry=np.array(list)

In [4]:
arry

array([1, 2, 3])

In [5]:
mat=[[1,2,3],[4,5,6],[7,8,9]]

In [6]:
mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
arry=np.array(mat)

In [8]:
arry

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
np.zeros((5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [12]:
np.ones((5,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
s=(5,2)
np.zeros(s)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
np.zeros((5), dtype=int)
#np.zeros((5), dtype=float)

array([0, 0, 0, 0, 0])

In [16]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [17]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [18]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.eye(1)

array([[1.]])

In [33]:
np.random.rand(2)

array([0.01083699, 0.74062241])

In [34]:
np.random.rand(20)

array([0.15463114, 0.71306831, 0.39650476, 0.57697297, 0.94584528,
       0.30721471, 0.59124329, 0.57090339, 0.55755149, 0.52665979,
       0.81205245, 0.53080342, 0.34448031, 0.19070123, 0.66181494,
       0.01158514, 0.65433473, 0.76412534, 0.51616278, 0.19035389])

# randn
Return a sample (or samples) from the "standaer normal" distribution. Unlike rand which is uniform

In [35]:
np.random.randn(5,5)

array([[-0.68603651, -0.91597468, -0.49207859,  0.37087395, -0.74761239],
       [ 0.97620186, -0.87043888,  0.11521842, -0.81357637,  0.4754062 ],
       [ 0.15792365, -0.51800532,  1.28923669, -0.88121438, -1.19957663],
       [ 1.57717741,  0.04892609, -3.00123162, -1.43664494,  3.10617468],
       [ 0.08150192,  0.64980905,  0.49668953,  0.01664325,  0.80088368]])

In [36]:
np.random.randn(20)

array([ 0.17660187, -0.48617489,  0.04512127,  0.1053378 , -0.71873228,
        0.83431022, -0.6953117 ,  0.68497518,  1.72473016,  0.68789951,
       -1.28197057,  0.04034595,  1.06937162, -1.59082176, -1.76720312,
       -0.35386334, -0.7640443 ,  0.22455829,  0.42940456,  0.73620783])

# randint
Return random intergers from low (inclusive) to high(exclusive)

In [37]:
np.random.randint(1,100)

57

In [38]:
np.random.randint(1,100,10)

array([64, 57, 19, 55, 21, 94, 65, 11,  7, 86])

# Array attributes and Mehods
Let's discuss some useful attributes and methods or an array

In [3]:
arr=np.arange(25)
ranarr=np.random.randint(0,50,10)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [41]:
ranarr

array([34,  8, 45, 45,  8, 15,  7, 23, 27, 37])

# Reshape
Returns an array containing the same data with a new shape.

In [43]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

NameError: name 'ranarr' is not defined