# max,min,argmax,argmin
These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax.

In [2]:
import numpy as np
ranarr=np.random.randint(0,50,10)
ranarr

array([16, 28, 14,  5, 25, 30, 22, 16, 38, 23])

In [9]:
ranarr.max()

47

In [10]:
#index number will be returned
ranarr.argmax()

6

In [11]:
ranarr.min()

5

In [12]:
ranarr.argmin()

7

# shape
shape is an attribute that arrays have (not a method)

In [4]:
arr=np.arange(25)
arr.shape

(25,)

In [10]:
# Notice the two sets of brackets
arr=arr.reshape(1,25)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [11]:
arr.shape

(1, 25)

In [23]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [24]:
arr.reshape(25,1).shape

(25, 1)

In [25]:
arr.dtype

dtype('int32')