# Question1

In [8]:
import numpy as np
np.version.version

'1.16.4'

# Question2

In [9]:
array1=np.arange(0,10)
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Question3

In [10]:
array2=np.ones((3,3),dtype=bool)
array2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

# Question4

In [11]:
array1[array1%2==1]

array([1, 3, 5, 7, 9])

# Question5  Question6

In [12]:
arrayA=array1
arrayA[arrayA%2==1]=-1
arrayA

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [13]:
array1

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

# Question7

In [14]:
array1.reshape(2,5)

array([[ 0, -1,  2, -1,  4],
       [-1,  6, -1,  8, -1]])

# Question8

In [15]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.stack([a,b])
c

array([[1, 2, 3],
       [4, 5, 6]])

# Question9

In [16]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.concatenate([a,b])
c

array([1, 2, 3, 4, 5, 6])

# Question10

In [17]:
a = np.array([1,2,3])
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

# Question11

In [18]:
a=np.array([1,2,3,4,5,6])
b=np.array([4,5,6,7,8,9])
# a=np.unique(a)
# b=np.unique(b)
# d=[]
# for i in a:
#     for j in b:
#         if i==j:
#             d.append(i)
#             break
# np.array(d)
np.intersect1d(a,b)

array([4, 5, 6])

# Question12

In [19]:
a=np.array([1,2,3,4,5,6,7,8,9])
b=np.array([4,4,5,6])
b=np.unique(b)
c=np.setdiff1d(a,b)
c

array([1, 2, 3, 7, 8, 9])

# Question13 (いまいちだなぁ…）

In [21]:
a=np.array([1,2,3,4,5,6,5])
b=np.array([4,5,6,7,8,9])
c=np.intersect1d(a,b)
d=[]
for i in c:
    index=0
    for j in a:
        if i==j:
            d.append(index)
        index+=1
np.sort(d)
# np.where(a==b)

array([3, 4, 5, 6])

# Question14(dtypeいらない）

In [46]:
a=np.arange(0,12)
a=np.where((a>=5) & (a<=10))
a

(array([ 5,  6,  7,  8,  9, 10], dtype=int64),)

# Question15

In [47]:
def maxx(a,b):
    c=np.concatenate([a,b])
    return c.max()
    

a=np.array([1,10.100])
b=np.array([20,21,22])
maxx(a,b)

22.0

# Question16

In [38]:
a=np.random.randn(4,5)
a

array([[-1.21534685,  2.05180274, -1.50488045, -1.26995214, -1.08421108],
       [-0.58127521,  0.06365086, -1.05620222,  0.09179428, -0.4121784 ],
       [-2.49556436,  1.23836415,  1.52028045, -1.39294775, -0.77406386],
       [ 1.7326397 , -0.47142092,  1.09283248, -0.18516796, -0.11344718]])

In [39]:
a=a.T
sha=a.shape
b=np.hstack((a[1],a[0]))
i=2
while  i<len(a):
    b=np.hstack((b,a[i]))
    i+=1
b.reshape(sha).T

array([[ 2.05180274, -1.21534685, -1.50488045, -1.26995214, -1.08421108],
       [ 0.06365086, -0.58127521, -1.05620222,  0.09179428, -0.4121784 ],
       [ 1.23836415, -2.49556436,  1.52028045, -1.39294775, -0.77406386],
       [-0.47142092,  1.7326397 ,  1.09283248, -0.18516796, -0.11344718]])

# Question17(これもなんか微妙）

In [27]:
a=np.random.randn(4,5)
a

array([[ 0.61919419,  0.08183231,  0.52331454, -0.43731265,  0.3844834 ],
       [ 1.27225457,  0.71282728,  1.44114677,  1.10422657, -1.6964672 ],
       [ 0.48182331, -0.0218576 ,  0.62399582, -0.29632779,  0.92195877],
       [ 1.24971354,  1.48430737, -2.4041301 ,  0.0789395 , -0.46710496]])

In [29]:
sha=a.shape
b=np.hstack((a[1],a[0]))
i=2
while  i<len(a):
    b=np.hstack((b,a[i]))
    i+=1
b.reshape(sha)

array([[ 1.27225457,  0.71282728,  1.44114677,  1.10422657, -1.6964672 ],
       [ 0.61919419,  0.08183231,  0.52331454, -0.43731265,  0.3844834 ],
       [ 0.48182331, -0.0218576 ,  0.62399582, -0.29632779,  0.92195877],
       [ 1.24971354,  1.48430737, -2.4041301 ,  0.0789395 , -0.46710496]])

# Question18

In [42]:
a=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
np.flip(a,axis=0)

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

# Question19

In [44]:
np.flip(a,axis=1)

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

# Question20

In [67]:
# np.random.randint(5,11,(5,3)).astype('f')
np.random.uniform(5,10,[5,3])

array([[6.72624109, 5.09879114, 5.68487178],
       [7.99286911, 8.73686127, 9.65471313],
       [9.84622626, 8.01875221, 5.14253662],
       [5.92868205, 6.62166285, 8.01158078],
       [9.53302545, 6.17070423, 7.94323986]])

# Question21

In [101]:
a=np.random.randn(5,5)
np.round(a,3)

array([[ 0.48429796, -0.32139452,  0.16198726, -0.79290797, -0.40790406],
       [ 0.91903688,  2.4151337 , -1.18662361,  0.12200745,  1.08909373],
       [ 1.31449409, -0.75568035, -1.09975213,  0.12323413,  1.0723395 ],
       [ 0.21997683,  0.36967443,  1.85828242,  0.39657502, -1.62119044],
       [ 0.49271241, -0.15999466,  1.2412439 ,  0.9328968 ,  0.47357649]])

# Question22

In [104]:
np.array([0.000000000000000034,1.234567890123456789])

array([3.40000000e-17, 1.23456789e+00])

In [107]:
np.set_printoptions(precision=100,suppress=True)
np.array([0.000000000000000034,1.234567890123456789])

array([0.000000000000000034, 1.2345678901234567  ])